### ISSUE TITLE
Add buttons for user to change brush colour

### ISSUE THREAD

**Issue by NataliaLKB** [wesort/whiteboard#15]
- [x] button for grey
- [x] button for turquoise
- [x] style buttons appropriately (however you prefer)

**Comment by NataliaLKB** [comment]
@wesort this hasn't been merged into master, so I am going to reopen the issue until it is. Thanks!

**Comment by wesort** [comment]
I see. Thanks.

**Comment by NataliaLKB** [comment]
This is now complete, and live. Closing issue!
