### ISSUE TITLE
Should we pick colours/ theme?

### ISSUE THREAD

**Issue by NataliaLKB** [wesort/whiteboard#2]

**Comment by wesort** [comment]
I think we should use a greyscale palette of and one key / feature colour.

**Comment by NataliaLKB** [comment]
That sounds great. How about turquoise, or yellow. Something summery.

**Comment by wesort** [comment]
Yup, I like summer.

How's this for a palette:
http://color.hailpixel.com/#9FDFBF,C4C4C4,3D3D3D,FAFAFA,

**Comment by NataliaLKB** [comment]
Beautiful. I like it :+1:

**Comment by NataliaLKB** [comment]
Set up a task #5. Closing this issue as question has been answered.
