### ISSUE TITLE
Start to apply colour scheme to whiteboard

### ISSUE THREAD

**Issue by NataliaLKB** [wesort/whiteboard#5]
Color Scheme: http://color.hailpixel.com/#9FDFBF,C4C4C4,3D3D3D,FAFAFA

Dependent on #3

**Comment by NataliaLKB** [comment]
What colour should the whiteboard be?

**Comment by wesort** [comment]
The background would be good as `#FAFAFA` I think.

**Comment by NataliaLKB** [comment]
That could be nice. Lets do it!

**Comment by NataliaLKB** [comment]
Assign yourself to the task if you want to do this :smile:

**Comment by wesort** [comment]
FYI: I noticed my CSS was working. So, based on your https://github.com/NataliaLKB/whiteboard-experiments/blob/master/_sass/_whiteboard.scss code, I am going to add a div around the `canvas` element and style that instead.

**Comment by NataliaLKB** [comment]
Sounds good!

**Comment by wesort** [comment]
I'm seeing scrollbars and I think our whiteboard should always be max-width & max-height of the viewport.

Here is what I'm seeing locally (27" screen and this window is made small)

![screenshot 2015-06-30 at 18 45 34](https://cloud.githubusercontent.com/assets/3920126/8437654/5db54b5c-1f58-11e5-9eb3-5e64b4bd4506.png)

**Comment by NataliaLKB** [comment]
@wesort since #16 can't be merged automatically (needs to be merged locally with master first), I am reopening the issue.

Issues should only be closed once the PR has been accepted.

**Comment by wesort** [comment]
Thanks - you're very clear with this stuff by the way.

**Comment by NataliaLKB** [comment]
:+1: . If I am ever not clear do let me know!

**Comment by NataliaLKB** [comment]
@wesort the canvas style branch has been merged and this issue looks good to close.
