### ISSUE TITLE
Make whiteboard full screen

### ISSUE THREAD

**Issue by NataliaLKB** [wesort/whiteboard#6]
Dependent on #3 

- [ ] We have a margin to the page margin: 1em;

**Comment by NataliaLKB** [comment]
I have already made it full screen, but yet to add the margin. Is this something you want to tackle? Or shall I?

**Comment by wesort** [comment]
I am happy to take ownership of CSS work as that's something I'm comfortable with.

Can I target `#canvas` from `style.css`?

**Comment by NataliaLKB** [comment]
You should be able to manipulate it just fine.

**Comment by wesort** [comment]
To clarify what we discussed, I don't think users should ever experience scrollbars. 

So, I have added `body { margin: 1em; }` to #19 which gives the canvas a light grey frame. I think this is enough.

**Comment by NataliaLKB** [comment]
@wesort I agree regarding scrollbars... I will push up a fix next week. Here is the bug #17 .
