### ISSUE TITLE
Should we be able to draw on the whiteboard with different colours?

### ISSUE THREAD

**Issue by NataliaLKB** [wesort/whiteboard#9]

**Comment by wesort** [comment]
Yes - One should be able to draw with a primary colour (I suggest `#3D3D3D`) and switch to the turquoise `#9FDFBF` to as an eye-catching "feature" colour.

How will users make the change between colours?

**Comment by NataliaLKB** [comment]
Great! I will do the js portion, if you could create and style the buttons? (do you think buttons are the best way to do this right now?)

**Comment by wesort** [comment]
Buttons sound good to me - simple to style and markup.

I will add buttons: 
- Grey Brush
- Turquois Brush

Top left, slightly rounded corners, flat UI (no gradients)?

**Comment by wesort** [comment]
I haven't added any id's to the buttons - thought you'd prefer to do that yourself.

In that regard, I will generally stick to styling with classes so that id's are available for your js to latch onto. Agreed?

**Comment by NataliaLKB** [comment]
@wesort as this is a question, I am taking myself off of assigned. 

I am happy to leave off ids full stop if you prefer!

**Comment by wesort** [comment]
Fair enough. I don't need ids either! 

Does this mean you will now close the issue or will it stay open until you've written the js?

**Comment by NataliaLKB** [comment]
task for the js part of this are here: #14 . I think this questions has been answered well. If you agree feel free to close the issue :smile: .

**Comment by wesort** [comment]
Gotcha.
